//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetPressBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BlogInfo
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "The field Title cannot be left empty")]
        public string Title { get; set; }
        public string Subtitle { get; set; }
        [Required(ErrorMessage = "The field Text cannot be left empty")]
        public string Text { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public short Status { get; set; }
        public int Category_Id { get; set; }
        public string Author_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
    }
}
